import { toast } from "sonner";
import {
  Plus,
  FileText,
  BarChart3,
  Briefcase,
  Download,
} from "lucide-react";
import { PageHeader } from "@/components/common/PageHeader";
import { StatusBadge } from "@/components/common/StatusBadge";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import {
  Table,
  TableHeader,
  TableHead,
  TableBody,
  TableRow,
  TableCell,
} from "@/components/ui/data-table";

// ---------------------------------------------------------------------------
// Mock data
// ---------------------------------------------------------------------------

const reportTypes = [
  {
    title: "Vendor Risk Report",
    description: "Single vendor detailed risk assessment with scoring breakdown.",
    icon: FileText,
  },
  {
    title: "Program Summary",
    description: "Overall program status, metrics, and trend analysis.",
    icon: BarChart3,
  },
  {
    title: "Executive Summary",
    description: "High-level overview of risk posture for leadership.",
    icon: Briefcase,
  },
];

const recentReports = [
  {
    id: 1,
    name: "Q2 2026 Vendor Risk - CloudSync Ltd.",
    type: "PDF" as const,
    generatedBy: "Sarah Chen",
    date: "Jun 25, 2026",
    size: "1.4 MB",
  },
  {
    id: 2,
    name: "Program Summary - June 2026",
    type: "PDF" as const,
    generatedBy: "James Walters",
    date: "Jun 20, 2026",
    size: "2.1 MB",
  },
  {
    id: 3,
    name: "Vendor Inventory Export",
    type: "CSV" as const,
    generatedBy: "Sarah Chen",
    date: "Jun 18, 2026",
    size: "348 KB",
  },
  {
    id: 4,
    name: "Executive Risk Brief - Board Meeting",
    type: "PDF" as const,
    generatedBy: "Michael Torres",
    date: "Jun 12, 2026",
    size: "890 KB",
  },
  {
    id: 5,
    name: "Remediation Tracking Export",
    type: "CSV" as const,
    generatedBy: "James Walters",
    date: "Jun 5, 2026",
    size: "215 KB",
  },
];

// ---------------------------------------------------------------------------
// Main Component
// ---------------------------------------------------------------------------

export default function ReportsPage() {
  return (
    <div className="space-y-5">
      {/* Header */}
      <PageHeader
        title="Reports"
        description="Generate and view risk reports and executive summaries."
      >
        <Button
          onClick={() => toast.info("Report generation", { description: "Select a report type below to generate." })}
        >
          <Plus className="h-4 w-4" />
          Generate Report
        </Button>
      </PageHeader>

      {/* Generate Report */}
      <div>
        <h2 className="text-sm font-semibold text-foreground mb-4">
          Generate Report
        </h2>
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {reportTypes.map((rt) => {
            const Icon = rt.icon;
            return (
              <Card key={rt.title} className="p-5">
                <div className="space-y-3">
                  <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
                    <Icon className="h-5 w-5 text-primary" />
                  </div>
                  <h3 className="text-sm font-semibold text-foreground">
                    {rt.title}
                  </h3>
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    {rt.description}
                  </p>
                  <Button
                    variant="secondary"
                    size="sm"
                    onClick={() => toast.info(`Generate ${rt.title}`, { description: "Report generation will be available with API integration." })}
                  >
                    Generate
                  </Button>
                </div>
              </Card>
            );
          })}
        </div>
      </div>

      {/* Recent Reports */}
      <Card>
        <CardHeader>
          <CardTitle>Recent Reports</CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Report Name</TableHead>
                <TableHead>Type</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead>Date</TableHead>
                <TableHead>Size</TableHead>
                <TableHead>Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {recentReports.map((report) => (
                <TableRow key={report.id}>
                  <TableCell className="font-medium text-foreground">
                    {report.name}
                  </TableCell>
                  <TableCell>
                    <StatusBadge
                      variant={report.type === "PDF" ? "info" : "success"}
                    >
                      {report.type}
                    </StatusBadge>
                  </TableCell>
                  <TableCell className="text-muted-foreground">
                    {report.generatedBy}
                  </TableCell>
                  <TableCell className="text-muted-foreground">
                    {report.date}
                  </TableCell>
                  <TableCell className="text-muted-foreground">
                    {report.size}
                  </TableCell>
                  <TableCell>
                    <Button
                      variant="ghost"
                      size="icon"
                      onClick={() => toast.info(`Download ${report.name}`, { description: "Download will be available with API integration." })}
                    >
                      <Download className="h-4 w-4" />
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
